[build]
  command = "npm run build:ssr"
  publish = "dist/pokemon-ssr/browser"

[functions]
  directory = "dist/pokemon-ssr/server"

[[edge_functions]]
  path = "/*"
  function = "netlifyCommonEngineHandler"
